export const runeSets: {[key: number]: string} = {
  1: 'Energy',
  2: 'Guard',
  3: 'Swift',
  4: 'Blade',
  5: 'Rage',
  6: 'Focus',
  7: 'Endure',
  8: 'Fatal',
  10: 'Despair',
  11: 'Vampire',
  13: 'Violent',
  14: 'Nemesis',
  15: 'Will',
  16: 'Shield',
  17: 'Revenge',
  18: 'Destroy',
  19: 'Fight',
  20: 'Determination',
  21: 'Enhance',
  22: 'Accuracy',
  23: 'Tolerance',
  24: 'Seal',
  25: 'Intangible',
  99: 'Immemorial'
}
